import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { styled } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';

export default function Home() {
	const Item = styled(Paper)(({ theme }) => ({
		...theme.typography.body2,
		padding: theme.spacing(1),
		textAlign: 'center',
		color: theme.palette.text.secondary,
	}));

	return (
		<div className={styles.container}>
			<Head>
				<title>Book Look</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				<h1 style={{ textAlign: 'center' }}>Book Look</h1>
			</div>
			<div>Search</div>
			<div style={{ marginTop: '60px' }}>
				<Grid container spacing={2}>
					<Grid item xs={3}>
						<Item style={{ color: 'black', border: '1px solid black' }}>
							Filter
						</Item>
					</Grid>
					<Grid item xs={8}>
						<Item style={{ color: 'black', border: '1px solid black' }}>
							Books
						</Item>
					</Grid>
				</Grid>
			</div>
		</div>
	);
}
