import Head from "next/head";
import styles from "../styles/Home.module.css";
import { styled } from "@mui/material/styles";
import Paper from "@mui/material/Paper";
import { useEffect, useState } from "react";
import AppBar from "../components/Decoration/Appbar";
import BookList from "../components/Lists/BookList";
import Filter from "../components/Filter";

export default function Home({ Message, Books }) {
  // console.log(Books);
  const [books, setBooks] = useState([]);
  useEffect(() => {
    setBooks(Books);
  });
  const Item = styled(Paper)(({ theme }) => ({
    ...theme.typography.body2,
    padding: theme.spacing(1),
    textAlign: "center",
    color: theme.palette.text.secondary,
  }));
  if (Message) {
    return <div>Connected</div>;
  }
  // useEffect(() => {
  //   document.body.style.backgroundColor = "#eeeeff";
  // }, []);
  return (
    <div className={styles.container} style={{}}>
      <Head>
        <title>Book Look</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />

      <div style={{ marginTop: "30px" }}>
        <Filter setBooks={setBooks} />
        <BookList booklist={books} />
      </div>
    </div>
  );
}
export async function getServerSideProps({ req, res }) {
  const mysqlClient = require("../utils/database_connection");

  const promise = new Promise((resolve, reject) => {
    mysqlClient.connect();
    mysqlClient.query("select * from books", (error, result, fields) => {
      if (error) {
        reject(error);
      } else {
        resolve(result);
      }
    });
    mysqlClient.end();
  });

  const result = await promise;

  const _result = [];
  for (let i = 0; i < result.length; i++) {
    let _res = JSON.stringify(result[i]);
    _res = JSON.parse(_res);
    _result.push(_res);
  }

  return {
    props: {
      Books: _result,
    },
  };
}
