use BookLook;
CREATE TABLE books(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    CATAGORY VARCHAR(1000) NOT NULL,
    TOPIC VARCHAR (1000) NOT NULL,
    AUTHOR VARCHAR(1000) NOT NULL,
    PUBLISHER VARCHAR(1000) NOT NULL,
    UPLOADER_ID INT NOT NULL,
    EDITION VARCHAR(256)
    -- UPLOAD_DATE DATE NOT NULL
     
)